FROM node:20-alpine

WORKDIR /usr/src/app

# Copiar archivos de configuración necesarios
COPY package*.json ./
COPY tsconfig.json ./
COPY jest.config.js ./
COPY .eslintrc.json ./
COPY .prettierrc ./

# Instalar dependencias (incluyendo las de desarrollo)
RUN npm ci

# Exponer el puerto 5000 (según requisitos)
EXPOSE 3000

# Comando para ejecutar en modo desarrollo
CMD ["npm", "run", "dev"] 